logging:
  level:
    root: INFO
    org.apache.kafka: WARN


exporter:
  cronExpression: ${CRON_EXPRESSION_BATCH:-}
  readChunkSize: ${READ_CHUNK_SIZE:10000}
  corePoolSize: ${CORE_POOL_SIZE:4}

blobstorage.api:
  baseUrl: ${API_BLOB_BASE_URL:https://apim.internal.dev.cstar.pagopa.it/storage/}
  containerName: ${API_BLOB_CONTAINER_NAME:cstar-hashed-pans}
  apiKey: ${API_BLOB_SUBSCRIPTION_KEY:1234567890}
  filename: ${API_BLOB_CARD_FILENAME:hashedPansNew.zip}

management:
  info.defaults.enabled: false
  endpoints.enabled-by-default: false
  endpoint:
    health:
      enabled: true
      probes:
        enabled: true
  defaults:
    metrics:
      export:
        enabled: false

spring:
  data:
    mongodb:
      uri: ${MONGODB_CONNECTION_URI:mongodb://localhost:27017}
      database: ${MONGODB_NAME:rtd}

  cloud:
    function.autodetect: false
    stream:
      bindings:
        exporterToPim-out-0:
          destination: ${KAFKA_RTD_SPLIT_TOPIC:rtd-split-by-pi}
          content-type: application/json
          binder: kafka-split-by-pi-binder
          producer:
            partitionKeyExpression: headers.partitionKey
            partitionCount: ${KAFKA_RTD_SPLIT_PARTITION_COUNT:1}

      kafka:
        binder:
          configuration:
            security.protocol: SASL_SSL
            sasl.mechanism: PLAIN

      binders:
        kafka-split-by-pi-binder:
          type: kafka
          environment.spring.cloud.stream.kafka:
            binder:
              brokers: ${KAFKA_RTD_SPLIT_BROKER:localhost:29095}
              requiredAcks: all
              configuration:
                sasl.jaas.config: ${KAFKA_RTD_SPLIT_SASL_JAAS_CONFIG}

