logging:
  level:
    root: INFO

exporter:
  cronExpression: ${CRON_EXPRESSION_BATCH:-}
  readChunkSize: ${READ_CHUNK_SIZE:10000}

blobstorage.api:
  baseUrl: ${API_BLOB_BASE_URL:https://api.dev.cstar.pagopa.it/storage/cstar-hashed-pans}
  containerName: ${API_BLOB_CONTAINER_NAME:cstar-hashed-pans}
  apiKey: ${API_BLOB_SUBSCRIPTION_KEY:1234567890}
  filename: ${API_BLOB_CARD_FILENAME:hashedPans.zip}

management:
  info.defaults.enabled: false
  endpoints.enabled-by-default: false
  endpoint:
    health:
      enabled: true
      probes:
        enabled: true
  defaults:
    metrics:
      export:
        enabled: false
spring:
  batch:
    jdbc:
      initialize-schema: always
  data:
    mongodb:
      uri: ${MONGODB_CONNECTION_URI:mongodb://localhost:27017}
      database: ${MONGODB_NAME:rtd}
