microservice-chart:
  namespace: "rtd"
  nameOverride: ""
  fullnameOverride: ""

  livenessProbe:
    handlerType: httpGet
    httpGet:
      path: /actuator/health/liveness
      port: 8080
    initialDelaySeconds: 60
    failureThreshold: 6
    periodSeconds: 10

  readinessProbe:
    handlerType: httpGet
    httpGet:
      path: /actuator/health/readiness
      port: 8080
    initialDelaySeconds: 60
    failureThreshold: 6
    periodSeconds: 10

  podAnnotations: { }

  deployment:
    create: true

  service:
    create: true
    type: ClusterIP
    ports:
      - 8080

  ingress:
    create: false

  serviceAccount:
    create: false
    annotations: {}
    name: ""

  podSecurityContext:
    seccompProfile:
      type: RuntimeDefault

  securityContext:
    allowPrivilegeEscalation: false

  envSecret:
    MONGODB_CONNECTION_URI: mongo-db-connection-uri
    APPLICATIONINSIGHTS_CONNECTION_STRING: appinsights-instrumentation-key
    API_BLOB_SUBSCRIPTION_KEY: rtd-internal-api-product-subscription-key
    KAFKA_RTD_SPLIT_SASL_JAAS_CONFIG: evh-rtd-split-by-pi-rtd-split-by-pi-producer-policy-rtd

  envConfig:
    CORE_POOL_SIZE: "4"
    APPLICATIONINSIGHTS_PREVIEW_PROFILER_ENABLED: "false"

  envConfigMapExternals:
    rtd-exporter:
      JAVA_TOOL_OPTIONS: JAVA_TOOL_OPTIONS
      APPLICATIONINSIGHTS_ROLE_NAME: APPLICATIONINSIGHTS_ROLE_NAME
      APPLICATIONINSIGHTS_INSTRUMENTATION_LOGGING_LEVEL: APPLICATIONINSIGHTS_INSTRUMENTATION_LOGGING_LEVEL
      APPLICATIONINSIGHTS_INSTRUMENTATION_MICROMETER_ENABLED: APPLICATIONINSIGHTS_INSTRUMENTATION_MICROMETER_ENABLED
      MONGODB_NAME: MONGODB_NAME
      CRON_EXPRESSION_BATCH: CRON_EXPRESSION_BATCH
      READ_CHUNK_SIZE: READ_CHUNK_SIZE
      API_BLOB_BASE_URL: API_BLOB_BASE_URL
      API_BLOB_CARD_FILENAME: API_BLOB_CARD_FILENAME
    rtd-split-by-pi-producer:
      KAFKA_RTD_SPLIT_TOPIC: KAFKA_RTD_SPLIT_TOPIC
      KAFKA_RTD_SPLIT_BROKER: KAFKA_RTD_SPLIT_BROKER
      KAFKA_RTD_SPLIT_PARTITION_COUNT: KAFKA_RTD_SPLIT_PARTITION_COUNT
