# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

pr:
  autoCancel: false
  branches:
    include:
      - main
      - develop
      - uat

pool:
  #vmImage: 'ubuntu-latest'
  vmImage: ubuntu-22.04

#variables:
#  MAVEN_CACHE_FOLDER: $(Pipeline.Workspace)/.m2/repository
#  MAVEN_OPTS: '-Dmaven.repo.local=$(MAVEN_CACHE_FOLDER)'

steps:
  #  - task: Cache@2
  #    inputs:
  #      key: 'maven | "$(Agent.OS)" | pom.xml'
  #      restoreKeys: |
  #        maven | "$(Agent.OS)"
  #        maven
  #      path: $(MAVEN_CACHE_FOLDER)
  #    displayName: Cache Maven local repo

  - task: SonarCloudPrepare@1
    displayName: 'Prepare SonarCloud analysis configuration'
    inputs:
      SonarCloud: '$(SONARCLOUD_SERVICE_CONN)'
      organization: '$(SONARCLOUD_ORG)'
      scannerMode: Other
      extraProperties: |
        sonar.projectKey=$(SONARCLOUD_PROJECT_KEY)
        sonar.projectName=$(SONARCLOUD_PROJECT_NAME)
  #        sonar.exclusions='**/enums/**, **/model/**, **/dto/**, **/*Constant*, **/*Config.java, **/*Scheduler.java, **/*Application.java, **/src/test/**, **/Dummy*.java'
  #  - task: DownloadSecureFile@1
  #    displayName: 'download settings.xml for Maven'
  #    name: settingsxml
  #    inputs:
  #      secureFile: '$(SETTINGS_XML_RO_SECURE_FILE_NAME)'
  #      retryCount: '2'

  # options: '-B -s $(settingsxml.secureFilePath) -Dmaven.test.failure.ignore=true'

  - task: Gradle@3
    displayName: 'Jacoco test report'
    inputs:
      gradleWrapperFile: 'gradlew'
      tasks: 'clean build jacocoTestReport'
      publishJUnitResults: true
      testResultsFiles: '**/TEST-*.xml'
      javaHomeOption: 'JDKVersion'
      jdkVersionOption: '1.17'
      sonarQubeRunAnalysis: false

  - bash: xmlReportPaths=$(find "$(pwd)" -path '*jacoco.xml' | sed 's/.*/&/' | tr '\n' ','); echo "##vso[task.setvariable variable=xmlReportPaths]$xmlReportPaths"
    displayName: finding jacoco.xml

  - task: Gradle@3
    inputs:
      gradleWrapperFile: 'gradlew'
      tasks: 'sonar'
      options: '-Dsonar.coverage.jacoco.xmlReportPaths=$(xmlReportPaths) -Dorg.gradle.jvmargs=-Xmx4096M'
      publishJUnitResults: false
      javaHomeOption: 'JDKVersion'
      jdkVersionOption: '1.17'
      sonarQubeRunAnalysis: true
      sqGradlePluginVersionChoice: 'build' # use gradle specified version

  - task: SonarCloudPublish@1
    inputs:
      pollingTimeoutSec: '300'